/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kompsdaurlatmhhjfwwj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvbXBzZGF1cmxhdG1oaGpmd3dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3NTAwNzMsImV4cCI6MjA4NTMyNjA3M30.jxQzqRf0FH-OjgVaQ1JCL5Dxd-kTekTjhXxu2VH2WlE"